[build]
publish = "."
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[functions."keep-alive"]
schedule = "*/12 * * * *"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
